<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="cvfdev" name="com.thalesgroup.services.cte.lis.dojo.Story7Test" tests="1" failures="1" timestamp="20 May 2016 10:06:39 GMT" time="0.207" errors="0">
  <testcase name="testValueOneSubregionOnly" time="0.207" classname="com.thalesgroup.services.cte.lis.dojo.Story7Test">
    <failure type="java.lang.AssertionError" message="Expected value &#039;2&#039; in cell (row=2,column=8) but obtained value &#039;0&#039; instead.">
      <![CDATA[java.lang.AssertionError: Expected value '2' in cell (row=2,column=8) but obtained value '0' instead.
	at org.testng.Assert.fail(Assert.java:94)
	at com.thalesgroup.services.cte.lis.dojo.SudokuTest$SolvedProblem$CellChecker.shallContain(SudokuTest.java:81)
	at com.thalesgroup.services.cte.lis.dojo.Story7Test.testValueOneSubregionOnly(Story7Test.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- testValueOneSubregionOnly -->
</testsuite> <!-- com.thalesgroup.services.cte.lis.dojo.Story7Test -->
